name: Build debian
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            libglfw3-dev \
            libturbojpeg0-dev \
            libusb-1.0-0-dev \
            libva-dev \
            ocl-icd-opencl-dev

      - name: Create a build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: build
        run: cmake -DCMAKE_INSTALL_PREFIX=/usr ..

      - name: Build the project
        working-directory: build
        run: make -j8

      - name: Build Debian package
        working-directory: build
        run: cpack

      - name: Save result
        if: ${{ github.event == 'pull_request' }}
        uses: actions/upload-artifact@v2.2.3
        with:
          name: package
          path: build/*.deb

      - name: Deploy Debian package to server
        if: ${{ github.event == 'pull_request' }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          source: "build/*.deb"
          target: "~/temp/nightly/"
          rm: true

      - name: Prepare Debian package in the server
        if: ${{ github.event == 'pull_request' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd ~/repository/debian
            reprepro includedeb nightly ~/temp/nightly/*.deb
